// Shared mapping from Supabase row → Property type (includes category model fields)
import { Property } from '@/types/property';

export function mapPropertyRow(item: any): Property {
  return {
    id: item.id,
    landlord_id: item.landlord_id,
    title: item.title || '',
    description: item.description || '',
    price: item.price || 0,
    property_type: item.property_type || 'other',
    listing_type: item.listing_type,
    listing_intent: item.listing_intent,
    asset_category: item.asset_category,
    property_subtype: item.property_subtype,
    price_period: item.price_period,
    location_city: item.location_city || '',
    location_suburb: item.location_suburb || '',
    location_address: item.location_address || '',
    latitude: item.latitude,
    longitude: item.longitude,
    bedrooms: item.bedrooms ?? undefined,
    bathrooms: item.bathrooms ?? undefined,
    size_sqm: item.size_sqm,
    is_furnished: item.is_furnished || false,
    land_size_ha: item.land_size_ha ?? undefined,
    land_size_sqm: item.land_size_sqm ?? undefined,
    is_fenced: item.is_fenced ?? undefined,
    has_road_access: item.has_road_access ?? undefined,
    has_water: item.has_water ?? undefined,
    has_electricity: item.has_electricity ?? undefined,
    has_sewer: item.has_sewer ?? undefined,
    zoning_notes: item.zoning_notes ?? undefined,
    floor_area_sqm: item.floor_area_sqm ?? undefined,
    floors: item.floors ?? undefined,
    parking_bays: item.parking_bays ?? undefined,
    fit_out: item.fit_out ?? undefined,
    has_loading_bay: item.has_loading_bay ?? undefined,
    has_street_frontage: item.has_street_frontage ?? undefined,
    power_notes: item.power_notes ?? undefined,
    amenities: item.amenities || [],
    lease_terms: item.lease_terms || '',
    tenure_type: item.tenure_type || 'unsure',
    status: item.status || 'active',
    is_featured: item.is_featured || false,
    views: item.views || 0,
    save_count: item.save_count,
    contact_count: item.contact_count,
    report_count: item.report_count,
    created_at: item.created_at,
    updated_at: item.updated_at,
    published_at: item.published_at,
    expires_at: item.expires_at,
    contact_phone: item.contact_phone || '',
    contact_whatsapp: item.contact_whatsapp || '',
    country: item.country || 'Eswatini',
    landlord: item.landlord || {
      full_name: 'Property Owner',
      phone: '',
      is_verified: false,
    },
    photos: item.photos || [],
  };
}
